-- Note: No Special Characters for Password

CREATE SCHEMA `front50` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'front50_service' IDENTIFIED BY 'OpsMx2022';
CREATE USER 'front50_migrate' IDENTIFIED BY 'OpsMx2022';
GRANT  SELECT, INSERT, UPDATE, CREATE, DELETE, EXECUTE, SHOW VIEW ON `front50`.*   TO 'front50_service';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, LOCK TABLES, EXECUTE, SHOW VIEW  ON `front50`.* TO 'front50_migrate';
